### ISSUE TITLE
Problema em ValorPorExtenso.

### ISSUE THREAD

**Issue by rhyan-jackson** [leovd100/Projetos-Python#1]
**Olá!**
Ao digitar um número com zeros antes o programa não funciona.

**Por exemplo:**
INPUT: 0008
_O script não identifica como o número 8, na verdade, ele manda eu repetir o dígito, sendo que não é o correto(na minha visão)._

**Resolução:** transforme o input do número pelo usuário em um número inteiro por meio do int() e depois defina-o como uma string novamente, isso tirará os zeros automaticamente do número e irá resolver o problema.

**Comment by leovd100** [comment]
Oi Rhyan, tudo bem ? 

Cara, valeu. Arrumei aqui e fiz algumas modificações. Se quiser testar, fique a vontade!
Esse código é bem antigo, faz 4 anos que não mexo nele, é normal ter erros kk.

Abraços!!

**Comment by rhyan-jackson** [comment]
Olá Leo, tudo ótimo.
Sem problemas kkkk, sou novo no Python e tô vagando por aí olhando sobre os projetos. Faz um bom tempo, imagino que você já esteja em outra vibe.
Abrações!
